    NKRO_ENABLE           = no # Enable N-Key Rollover
    AUTOCORRECT_ENABLE    = yes
    CAPS_WORD_ENABLE      = yes
    TAP_DANCE_ENABLE      = yes
    TRI_LAYER_ENABLE      = no
    AUTO_SHIFT_ENABLE     = no
    COMBO_ENABLE          = yes
    VIA_ENABLE            = no
    VIAL_ENABLE           = no
    VIALRGB_ENABLE        = no
    SRC += features/sentence_case.c
    SRC += features/repeat_key.c
